#!/usr/bin/env bash

: ${KINDLE_MAIL:="${1:=""}"}
[[ -z "$KINDLE_MAIL" ]] && { echo "kindle mail address needs to be specified"; exit 1; }

TEMP_FILE="$(mktemp)"

parallel --keep-order \
  "wget \
    --quiet \
    --output-document=- \
    '{}'" \
  | pandoc \
    --standalone \
    --from=html \
    --to=html \
    --toc \
    --toc-depth 2 \
    --output=${TEMP_FILE}.html

ebook-convert \
  ${TEMP_FILE}.html \
  ${TEMP_FILE}.mobi \
  --use-auto-toc \
  --output-profile kindle \
  >/dev/null 2>&1
  # --use-auto-toc \

echo "body" \
  | mutt \
    -F ~/sinan/git_repos/dotfiles/imap_muttrc \
    -s "ebooks" \
    -a ${TEMP_FILE}.mobi \
    -- ${KINDLE_MAIL}

rm -f ${TEMP_FILE} ${TEMP_FILE}.html ${TEMP_FILE}.mobi

