#!/usr/bin/env bash

: ${KINDLE_MAIL:="${1:=""}"}
[[ -z "$KINDLE_MAIL" ]] && { echo "kindle mail address needs to be specified"; exit 1; }

TEMP_FILE="$(mktemp)"

insert_title_script="$(dirname $(realpath $0))/insert_h1_title"

echo "download links" >&2

parallel --keep-order \
  "wget \
    --quiet \
    --output-document=- \
    '{}' \
    | $insert_title_script " \
  | pandoc \
    --standalone \
    --from=html \
    --to=html \
    --toc \
    --toc-depth 2 \
    --output=${TEMP_FILE}.html

echo "converting ebooks" >&2

ebook-convert \
  ${TEMP_FILE}.html \
  ${TEMP_FILE}.mobi \
  --output-profile kindle \
  >/dev/null 2>&1
  # --use-auto-toc \

echo "sending ebook" >&2

echo "body" \
  | mutt \
    -F ~/sinan/git_repos/dotfiles/imap_muttrc \
    -s "ebooks" \
    -a ${TEMP_FILE}.mobi \
    -- ${KINDLE_MAIL}

rm -f ${TEMP_FILE} ${TEMP_FILE}.html ${TEMP_FILE}.mobi

